### ISSUE TITLE
url des DOI ne semblent pas corrects

### ISSUE THREAD

**Issue by EdouardSombie** [CNRS-LACITO/eastlingeditor#14]
Dans le player, les DOI mènent vers une adresse du type :
https://pangloss.cnrs.fr/corpus/citation_doi.php?https://doi.org/10.24397/pangloss-0004342&amp;sentence=S1

**Comment by alexis-michaud** [comment]
Hello,
Où en est-on pour ce ticket ? À fermer / rattacher à un autre ? À discuter ensemble ?

**Comment by m8nli9ht** [comment]
Je ne vois pas d'erreur dans les DOI pour ce document. Ticket déjà traité et à clôturer ?

**Comment by alexis-michaud** [comment]
Bien vu @m8nli9ht !
