### ISSUE TITLE
formatage de la boîte des paramètres

### ISSUE THREAD

**Issue by EdouardSombie** [CNRS-LACITO/eastlingeditor#15]
Il faudrait mettre dans un même conteneur le nom du paramètre et les options qui s'y rattachent.

Ex: 
<legend class="MuiFormLabel-root">Translations</legend>
<div class="MuiFormGroup-root">...</div>

Devrait être
<div class="form-group">
<legend class="MuiFormLabel-root">Translations</legend>
<div class="MuiFormGroup-root">...</div>
</div>

**Comment by alexis-michaud** [comment]
Hello, 
Où en est-on pour ce ticket ? À fermer / rattacher à un autre ? À discuter ensemble ?

**Comment by alexis-michaud** [comment]
Re-hello, 
@m8nli9ht petit rappel après 6 mois ;) Ticket à fermer ? À discuter ?
