### ISSUE TITLE
import depuis site Pangloss

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/eastlingeditor#45]
Premier test de l'import depuis site Pangloss !!

Et tout de suite, une amélioration à faire qui ressort :) 
![image](https://user-images.githubusercontent.com/6072524/221953287-9ef59e0b-5b02-4956-a127-5186e3bf5c46.png)

À faire : monter la limite supérieure autorisée pour les chaînes de caractères ? 
Il faut autoriser les chaînes longues en prenant comme limite supérieure la traduction ou transcription intégrale d'un texte : la `<FORM>` ou `<TRANSL>` au niveau `<TEXT>`. Pour un bon gros récit d'une demi-heure, ça peut aller chercher dans les 50 000 caractères ou plus. (Un exemple au-dessus de 30k caractères : la traduction française du texte [en fin de ce document](https://github.com/alexis-michaud/na/blob/master/TEXT/F4/crdo-NRU_F4_HOUSEBUILDING2.xml).)

**Comment by m8nli9ht** [comment]
Ok je m'en occupe demain, il s'agit de redimensionner le champ de table

**Comment by m8nli9ht** [comment]
J'ai modifié le type de champ de VARCHAR vers TEXT pour permettre 50000 char.
A tester.

**Comment by alexis-michaud** [comment]
Nouvelle tentative pour le même document : 
https://doi.org/10.24397/pangloss-0004341

![image](https://user-images.githubusercontent.com/6072524/224292157-1a515fb0-68e7-4c1e-a24e-4f80a6428e4a.png)

**Comment by alexis-michaud** [comment]
Parfois ça reste figé (pendant plus de 30 minutes) sur l'étape d'avant, et ça n'avance plus : 
![image](https://user-images.githubusercontent.com/6072524/224312142-5e8cea6b-d0f9-4e79-8b7d-1ad7f6602657.png)

**Comment by m8nli9ht** [comment]
ok, il s'agit d'un problème de redirection suite à l'import, je vais corriger.

**Comment by alexis-michaud** [comment]
C'est un vocabulaire contrôlé, celui de [OLAC](http://www.language-archives.org/)
En passant par ici : 
http://www.language-archives.org/REC/olac-extensions.html#role
on parvient à la liste (fermée) des rôles : 

[annotator](http://www.language-archives.org/REC/role.html#annotator)
[author](http://www.language-archives.org/REC/role.html#author)
[compiler](http://www.language-archives.org/REC/role.html#compiler)
[consultant](http://www.language-archives.org/REC/role.html#consultant)
[data_inputter](http://www.language-archives.org/REC/role.html#data_inputter)
[depositor](http://www.language-archives.org/REC/role.html#depositor)
[developer](http://www.language-archives.org/REC/role.html#developer)
[editor](http://www.language-archives.org/REC/role.html#editor)
[illustrator](http://www.language-archives.org/REC/role.html#illustrator)
[interpreter](http://www.language-archives.org/REC/role.html#interpreter)
[interviewer](http://www.language-archives.org/REC/role.html#interviewer)
[participant](http://www.language-archives.org/REC/role.html#participant)
[performer](http://www.language-archives.org/REC/role.html#performer)
[photographer](http://www.language-archives.org/REC/role.html#photographer)
[recorder](http://www.language-archives.org/REC/role.html#recorder)
[researcher](http://www.language-archives.org/REC/role.html#researcher)
[research_participant](http://www.language-archives.org/REC/role.html#research_participant)
[responder](http://www.language-archives.org/REC/role.html#responder)
[signer](http://www.language-archives.org/REC/role.html#signer)
[singer](http://www.language-archives.org/REC/role.html#singer)
[speaker](http://www.language-archives.org/REC/role.html#speaker)
[sponsor](http://www.language-archives.org/REC/role.html#sponsor)
[transcriber](http://www.language-archives.org/REC/role.html#transcriber)
[translator](http://www.language-archives.org/REC/role.html#translator)

**Comment by alexis-michaud** [comment]
Toujours une erreur à l'importation, sur ma machine : 
![image](https://user-images.githubusercontent.com/6072524/228886963-0f5281a8-d127-47f8-9839-d5e900185604.png)
Document concerné : 
Primary OAI
cocoon-3f7d934e-f69a-49bc-bd93-4ef69ad9bcba

Secondary OAI
cocoon-9c3f6e3f-8d2b-4cba-bf6e-3f8d2b5cbac5

**Comment by alexis-michaud** [comment]
En revanche pour celui-ci, ça marche !!
https://doi.org/10.24397/pangloss-0004661
![image](https://user-images.githubusercontent.com/6072524/228894290-618dc879-df3f-4dae-bc66-725003491e2a.png)

Super, je vais pouvoir tester !

**Comment by m8nli9ht** [comment]
Pour l'erreur pendant l'import des Annotations, il s'agit de balises <TRANSL> dont la propriété "xml:lang" n'est pas présente au niveau des mots. J'imagine que c'est parce qu'une seule langue est précisée au niveau supérieur (phrase) et que c'est donc la même au niveau inférieur

**Comment by alexis-michaud** [comment]
> Pour l'erreur "Error updating document" il s'agit d'un problème de format de date (une année '1995' seulement est donnée. Je vais voir comment gérer cette donnée

Je crois qu'il y a 3 formats autorisés dans les métadonnées de Cocoon : YYYY ou YYYY-MM ou YYYY-MM-DD.
Encore une petite complexité... mais quand elles s'additionnent, ça fait bcp à gérer :disappointed_relieved:

**Comment by alexis-michaud** [comment]
> Pour l'erreur pendant l'import des Annotations, il s'agit de balises dont la propriété "xml:lang" n'est pas présente au niveau des mots. J'imagine que c'est parce qu'une seule langue est précisée au niveau supérieur (phrase) et que c'est donc la même au niveau inférieur

Vi, c'est ça. Tout à fait.
Ca serait qd même plus propre de tout coder. J'ai un peu oublié où on en était de la réflexion : est-ce qu'on s'était dit qu'à l'ouverture (importation) d'un document avec l'éditeur Eastling, on proposerait d'ajouter le `xml:lang` là où il n'est pas présent.

**Comment by m8nli9ht** [comment]
J'ai corrigé les 2 erreurs, cependant une nouvelle est survenue et pour la quelle je ne peux pas faire grand chose avec mon hégerbeur actuel (avec l'abonnement basique que j'ai) : le temps d'exécution maximum alloué est de 60 secondes et pour des gros documents comme celui-ci (Primary OAI cocoon-3f7d934e-f69a-49bc-bd93-4ef69ad9bcba, Secondary OAI cocoon-9c3f6e3f-8d2b-4cba-bf6e-3f8d2b5cbac5, 150 phrases) le script tombe en erreur. N'ayant pas de nouvelles de Huma-Num sur la résolution du bug SSL, je ne peux pas encore migrer Eastling sur leur serveur !

**Comment by alexis-michaud** [comment]
Dur dur ! 
Courage & patience... :satellite: Il n'est pas rare ni incompréhensible qu'il y ait un délai de réponse côté Huma-Num.
Pour l'heure, c'est noté : on travaille sur les documents courts.
(L'affichage en temps réel du pourcentage du document qui a été traité est super ! Clair et rassurant.)
![image](https://user-images.githubusercontent.com/6072524/229272358-a35709c7-f673-4de6-8af2-670c987c4d0c.png)

**Comment by alexis-michaud** [comment]
> > Pour l'erreur "Error updating document" il s'agit d'un problème de format de date (une année '1995' seulement est donnée. Je vais voir comment gérer cette donnée
> 
> Je crois qu'il y a 3 formats autorisés dans les métadonnées de Cocoon : YYYY ou YYYY-MM ou YYYY-MM-DD. Encore une petite complexité... mais quand elles s'additionnent, ça fait bcp à gérer disappointed_relieved

En fait j'avais répondu vite fait mais le format des dates est encore plus sophistiqué que ça : non seulement il peut y avoir 3 formats (YYYY ou YYYY-MM ou YYYY-MM-DD), mais en plus, il est possible d'indiquer une plage de temps, quand on est pas sûr de la date. 
"parfois, la date n'est pas une date précise mais une période. Dans ces cas là ça se présente sous cette forme : `start=1950; end=1955;`" (décrit [ici](https://github.com/CNRS-LACITO/Pangloss_website/issues/198))

**Comment by alexis-michaud** [comment]
Nouvelle tentative, avec ce document : 

https://pangloss.cnrs.fr/corpus/show?corpus=Yongning_Na&oai_primary=cocoon-e101b0bd-68e9-3f2a-91ff-0ce81e3019be&oai_secondary=cocoon-9e11285b-cb3e-359c-825b-146477ada21a&lang=fr&mode=normal&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=autre&optionWordTranslations=zh&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false

oai_primary=cocoon-e101b0bd-68e9-3f2a-91ff-0ce81e3019be
oai_secondary=cocoon-9e11285b-cb3e-359c-825b-146477ada21a

L'importation se fait sans encombres. Mais il semble que les annotations ne soient pas lues : l'onglet "Annotations" est vide, semble-t-il ?

![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/c8f03696-cf00-4ccf-97f5-831cccdf004d)

Est-ce parce qu'il s'agit d'un document de type WORDLIST et non TEXT ?

**Comment by m8nli9ht** [comment]
J'ai retenté l'import de ce document depuis la migration sur Huma-Num et désormais j'ai l'impression que ça fonctionne. A tester de nouveau !

**Comment by Balthazar45** [comment]
Je confirme que cela focntion de mon côté : 
<img width="1337" alt="Capture d’écran 2023-09-28 à 16 17 29" src="https://github.com/CNRS-LACITO/eastlingeditor/assets/53433279/0dd68248-db3a-44f6-9a56-5dcea9a9ddc9">

**Comment by alexis-michaud** [comment]
:+1:
