### ISSUE TITLE
Export annotations au format XML │ nommage .XML

### ISSUE THREAD

**Issue by Balthazar45** [CNRS-LACITO/eastlingeditor#47]
Bonjour,
Lors de l’export des annotations d’un document au format XML (bouton XML Annotations), le titre du XML en sortie est intitulé par exemple : eastling-ddn_Dendi_TEXT-33.xml
                            
![Capture d’écran 2023-06-14 à 10 25 19](https://github.com/CNRS-LACITO/eastlingeditor/assets/53433279/b68fe039-b7da-45c1-a464-a40301a211f3)

Idem, dans l'identifiant de la balise `<TEXT>`, du xml récupéré.

Serait-il possible de récupérer l’intitulé de la ressource audio, par exemple "cocoon.huma-num.fr/data/tersis/nt_dendi_karimama_68_A_conte1.mp3"

ou celle du fichier XML d’annotation déjà déposé sur la base de donnée de CoCoon ?
Merci !

**Comment by m8nli9ht** [comment]
On peut récupérer le nom du XML ou le nom de l'audio (mais je ne pense pas que ça soit une bonne option car on aura des cas d'annotations d'images sans audio). 
Un idée : on propose à l'utilisateur de saisir le nom qu'il souhaite pour le fichier.
Qu'en pensez-vous ?

**Comment by alexis-michaud** [comment]
Serait-il possible, partant de la proposition de @Balthazar45, d'avoir une "cascade de décision" comme suit ? 
- si le XML existait déjà : on garde le nom antérieur
- à défaut, s'il y a un fichier audio, on reprend le nom de fichier et on substitue ".xml" à l'extension du fichier son (".wav", ".mp3" etc.) : par exemple, de `nt_dendi_karimama_68_A_conte1.mp3` à `nt_dendi_karimama_68_A_conte1.xml`
- à défaut, s'il y a un fichier image, on reprend le nom du fichier image, en substituant l'extension .xml

Dans tous les cas, l'utilisatrice peut modifier le titre avant de valider, comme quand on enregistre un fichier dans la majorité des applications : un nom de fichier est proposé mais on peut le modifier dans la fenêtre d'enregistrement
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/bec9896b-9b52-40f4-890c-5bf66a3cc9b6)

**Comment by Balthazar45** [comment]
Il est en effet important de conserver les conventions de nommage, surtout lorsque les ressources et les annotations proviennent d'un import depuis les dépôts réalisés sur la collection Pangloss.

**Comment by m8nli9ht** [comment]
c'est clair pour moi

**Comment by m8nli9ht** [comment]
Traité et livré, à tester

**Comment by alexis-michaud** [comment]
Premier retour : 
1) premier test (document sans annotation) : ça fonctionne.
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/20beec67-3eb8-4337-9eb2-6e2ae9ba46bd)
Un détail : il semble que le fichier fourni à l'export n'ait pas d'extension.
Serait-il possible d'indiquer une extension .xml, comme il convient à un fichier XML ?

2) En faisant un 2e test, pour un vrai document XML existant : 
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/f372c4c9-30f1-444b-b335-f49f9bcae1f8)
le site "mouline" brièvement
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/e2f7e033-b749-48e4-85b0-71ae4ad66985)
puis revient à l'affichage antérieur
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/cd6d5616-df68-4270-b820-c5af918e108f)
Aucun fichier n'a été exporté.

**Comment by m8nli9ht** [comment]
Ok je vois ce qu'il manque pour le premier cas. 
Je regarde ce qui ne va pas pour le second cas

**Comment by alexis-michaud** [comment]
Le souci (site qui mouline sans résultat) est similaire pour un autre document, [ici](https://pangloss.cnrs.fr/corpus/show?corpus=Yongning_Na&oai_primary=cocoon-e101b0bd-68e9-3f2a-91ff-0ce81e3019be&oai_secondary=cocoon-9e11285b-cb3e-359c-825b-146477ada21a&lang=fr&mode=normal&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=autre&optionWordTranslations=zh&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false). À ceci près que dans ce cas-ci, ça "mouline" sans s'arrêter : on n'arrive pas à l'étape "retour à la case départ" (même après plusieurs minutes).
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/5e819069-bfa8-4d1c-a9b6-fcf13e8672f5)

(Ce document est mentionné en lien avec la question de l'import dans Eastling [ici](https://github.com/CNRS-LACITO/eastlingeditor/issues/45#issuecomment-1662229319).)

**Comment by m8nli9ht** [comment]
Traité, livré, à tester

**Comment by alexis-michaud** [comment]
Pour moi ça marche :+1:
Au chargement d'un nouveau document, le nom du fichier XML de départ est conservé, et utilisé automatiquement lorsqu'on exporte le XML modifié.
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/5ffd3e1f-b5a3-4288-b9ff-7dc2d1802390)

**Comment by Balthazar45** [comment]
Pour moi cela marche également.
Lors de l'import d'un document déjà déposé sur la collection Pangloss, le nom du fichier XML de départ est bien conservé.
Puis il est bien réutilisé lors de l'export (au format XML) du même document retravaillé et modifié.
<img width="1135" alt="Capture d’écran 2023-09-28 à 16 03 26" src="https://github.com/CNRS-LACITO/eastlingeditor/assets/53433279/781c47f9-3790-4ce0-8a06-d5ca16e6f9a8">
