### ISSUE TITLE
Lien depuis hébergement ancien

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/eastlingeditor#5]
@m8nli9ht 

Pourrais-tu établir un lien vers l'hébergement actuel de EASTling depuis l'[hébergement précédent](https://github.com/m8nli9ht/eastling) ? 

Comme ce qu'a fait par exemple @vasaura pour le code "[DOI Pangloss](https://github.com/CNRS/DoiPangloss)", depuis [le dépôt GitHub où elle l'avait créé](https://github.com/vasaura/DoiPangloss).

**Comment by m8nli9ht** [comment]
Bonjour Alexis,

Je serai disponible cet après-midi à 16h pour un call.
Ce créneau te conviendrait-il ?

Matthew

Le dim. 3 mai 2020 à 16:56, Alexis Michaud <notifications@github.com> a
écrit :
