### ISSUE TITLE
Phase d’annotation │ Déconnexions 

### ISSUE THREAD

**Issue by Balthazar45** [CNRS-LACITO/eastlingeditor#50]
Lors du travail d’annotation, l'utilisateur sort de l’éditeur sans être prévenu, après une certaine durée de travail.
Cette déconnexion se produit même si le travail est en train de se poursuivre.
Serait-il possible d’afficher une alerte avant déconnexion ?
Merci !

**Comment by m8nli9ht** [comment]
Test en cours avec changement du fichier de config .env sur paramètre JWT_TTL

**Comment by m8nli9ht** [comment]
Traité et livré, à tester

**Comment by Balthazar45** [comment]
Bonjour,
Je viens de faire l'essai et cela fonctionne maintenant sur une période d'une heure de connexion.
 Merci !
