### ISSUE TITLE
migration vers espace eastling.huma-num.fr

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/eastlingeditor#52]
[L'espace est prêt](https://eastling.huma-num.fr/)
![image](https://github.com/CNRS-LACITO/eastlingeditor/assets/6072524/a32e18bc-28d5-48d7-970a-d6db2a88eab2)

Migration en attente de la mise en place des outils dont Eastling a besoin ?

@sguillaume @m8nli9ht mises à jour bienvenues si des infos étaient disponibles

**Comment by alexis-michaud** [comment]
Souci de connexion au serveur mySQL d'Huma-Num depuis un Eastling installé sur les serveurs d'Huma-Num : souci de certificat de sécurité ?

**Comment by alexis-michaud** [comment]
Migration nécessaire pour le bon fonctionnement de l'export sous forme de livrets (bon dialogue entre serveurs) : [ticket #63 du lecteur Eastling](https://github.com/CNRS-LACITO/eastlingplayer/issues/63)

**Comment by m8nli9ht** [comment]
serveur MySQL mysql80a.db.huma-num.fr

**Comment by m8nli9ht** [comment]
La configuration SSL semble être OK (j'ai récupéré celle d'Edouard sur Pangloss). Maintenant, configuration Apache à modifier (demande de modif de l'alias /api/ vers le dossier root, en cours ce jour auprès de Gérald Foliot)

**Comment by m8nli9ht** [comment]
Le changement de paramètrage d'alias apache a été modifié (l'ancien alias qui pointait vers le dossier /public a été supprimé), et tout fonctionne sur Huma-Num.fr

**Comment by alexis-michaud** [comment]
Question : pourquoi la page d'accueil est vide?
(Juste un souci d'affichage sur mon poste ?)

**Comment by m8nli9ht** [comment]
Exact, en fait l'éditeur est accessible dans le sous-dossier /editor:

Https://eastling.​huma-num.​fr/editor

En fait, j'ai aussi le sous-dossier /api pour le côté backend de
l'application (/editor étant l'interface).

Je vais faire en sorte de rediriger automatiquement vers l'accueil de
l'éditeur !

Le jeu. 21 sept. 2023 à 17:31, Alexis Michaud ***@***.***> a
écrit :

**Comment by m8nli9ht** [comment]
c'est fait!
